// <auto-generated />
using ApplicationBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApplicationBackend.Migrations
{
    [DbContext(typeof(ClubContext))]
    [Migration("20190322132343_SomeDataAdded")]
    partial class SomeDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApplicationBackend.Models.ClubModelClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AwayKitColour")
                        .IsRequired();

                    b.Property<int>("ChampionsLeague");

                    b.Property<double>("ClubValue");

                    b.Property<int>("EuropaLeague");

                    b.Property<int>("FaCup");

                    b.Property<string>("HomeKitColour")
                        .IsRequired();

                    b.Property<int>("LeagueCup");

                    b.Property<int>("PremierLeague");

                    b.Property<string>("TeamName")
                        .IsRequired();

                    b.Property<string>("ThirdKitColour");

                    b.HasKey("Id");

                    b.ToTable("ClubModelClass");
                });
#pragma warning restore 612, 618
        }
    }
}
